import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Netlify's build scratch: its Next runtime vendors Deno and @types/node
    // sources under .netlify during the build, and the gate runs eslint after
    // the build — 1,230 errors in code nobody here wrote. Only ever exists on
    // the build machine, which is why no local run ever saw it.
    ".netlify/**",
    // Its own toolchain and its own globals — checked by `npm run check`
    // inside workers/inbound-email, not by the app's config.
    "workers/**",
    // Prisma's generated client.
    "src/lib/generated/**",
    // Generated by scripts/generate-swoosh-samples.mjs: 83KB of base64 on
    // one line, which is data, not code — the parser has nothing to say
    // about it beyond a stack overflow.
    "src/components/decor/swoosh-samples.ts",
    // Generated by scripts/generate-atlas-terrain.mjs: the /studio map's
    // terrain SVG as one long string, same deal as the swoosh samples.
    "src/components/studio/atlas-terrain.ts",
    // Design-lab prototypes and a vendored decoder, ignored 2026-08-22 so CI
    // can require zero errors: they predate the merge, ship on no production
    // route that matters, and fixing them is design work, not lint work.
    // Remove these lines the day the labs graduate or get deleted.
    "src/components/relief/**",
    "public/draco/**",
  ]),
]);

export default eslintConfig;
