/** One source for the SEO page's questions: the visible accordion and its FAQ schema. */
export const seoFaqs = [
  { id: "site-access", question: "Is my existing website suitable?", answer: "We start by reviewing your current website and arranging authorised access, or working with your website manager. If the site needs replacing, we’ll explain why and discuss the options.", link: { href: "/web-design", label: "Explore web design →" } },
  { id: "included", question: "What’s included, and what does it cost?", answer: "Core is £995/month for agreed content, technical SEO, relevant authority work and website improvements, with monthly reporting. Hosting, security and support are included for agreed managed sites. A higher-capacity tier is £2,995/month.", link: { href: "/pricing#options", label: "Compare pricing →" } },
  { id: "ai-search", question: "Is AI search included?", answer: "Yes. AEO — answer engine optimisation — is part of the SEO work. We research customer questions, create useful answers, improve page structure and use suitable structured data. We review available AI visibility alongside organic search; appearances and citations cannot be guaranteed." },
  { id: "google-ads", question: "Is Google Ads included?", answer: "Core includes a £400 Google Ads trial funded by Valinor. We review the results with you before you decide whether to continue.", link: { href: "/google-ads", label: "How we manage Google Ads →" } },
  { id: "progress", question: "How do we assess progress?", answer: "We record a starting point, agree priorities and report what changed each month. We look at available search visibility, relevant visits and reliable enquiry data, then use the findings to decide the next work. A monthly strategy review call is available at your discretion. Timing depends on your starting point, competition and the changes needed." },
  { id: "minimum-term", question: "What’s the minimum term?", answer: "Three months from kickoff, including any build time, with fees paid in advance. After that, service continues monthly with 30 days’ written notice. Paying six months of SEO before kickoff waives the agreed website build fee; managed ownership and transfer conditions still apply.", link: { href: "/pricing#payments", label: "Payment and website terms →" } },
] as const;
